defmodule WandererOps.Repo.Migrations.AddMapColor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :color, :text
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :color
    end
  end
end
