defmodule WandererOps.Repo.Migrations.AddMapIsMain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :is_main, :boolean
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :is_main
    end
  end
end
