defmodule WandererOps.Repo.Migrations.AddMapShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_share_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_share_links_map_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:map_share_links, [:token], name: "map_share_links_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:map_share_links, [:token],
                     name: "map_share_links_unique_token_index"
                   )

    drop constraint(:map_share_links, "map_share_links_map_id_fkey")

    drop table(:map_share_links)
  end
end
