defmodule WandererOps.Repo.Migrations.AddPasswordAndDescriptionToShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:share_links) do
      add :password_hash, :text
      add :description, :text
    end
  end

  def down do
    alter table(:share_links) do
      remove :description
      remove :password_hash
    end
  end
end
