defmodule WandererOps.Repo.Migrations.AddMapInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :map_url, :text
      add :public_api_key, :text
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :public_api_key
      remove :map_url
    end
  end
end
