defmodule WandererOps.Repo.Migrations.AddMapMainSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :main_system_eve_id, :bigint
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :main_system_eve_id
    end
  end
end
