defmodule WandererOps.Repo.Migrations.AddShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:share_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:share_links, [:token], name: "share_links_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:share_links, [:token], name: "share_links_unique_token_index")

    drop table(:share_links)
  end
end
