defmodule WandererOps.Repo.Migrations.AddSnapshotToShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:share_links) do
      add :is_snapshot, :boolean, null: false, default: false
      add :snapshot_data, :map
      add :snapshot_at, :utc_datetime
    end
  end

  def down do
    alter table(:share_links) do
      remove :snapshot_at
      remove :snapshot_data
      remove :is_snapshot
    end
  end
end
